# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Finder_mk3.ui'
##
## Created by: Qt User Interface Compiler version 5.15.8
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *  # type: ignore
from PySide2.QtGui import *  # type: ignore
from PySide2.QtWidgets import *  # type: ignore


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(524, 418)
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 201, 502, 101))
        self.groupBox_3.setMinimumSize(QSize(0, 80))
        font = QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.groupBox_3.setFont(font)
        self.textBrowser__save = QTextBrowser(self.groupBox_3)
        self.textBrowser__save.setObjectName(u"textBrowser__save")
        self.textBrowser__save.setGeometry(QRect(12, 40, 391, 41))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setItalic(False)
        self.textBrowser__save.setFont(font1)
        self.buttonBox__save = QDialogButtonBox(self.groupBox_3)
        self.buttonBox__save.setObjectName(u"buttonBox__save")
        self.buttonBox__save.setEnabled(True)
        self.buttonBox__save.setGeometry(QRect(410, 50, 80, 24))
        self.buttonBox__save.setFont(font)
        self.buttonBox__save.setOrientation(Qt.Horizontal)
        self.buttonBox__save.setStandardButtons(QDialogButtonBox.Save)
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 8, 341, 81))
        self.label__keyword = QLabel(self.groupBox)
        self.label__keyword.setObjectName(u"label__keyword")
        self.label__keyword.setGeometry(QRect(10, 32, 61, 17))
        self.label__keyword.setFont(font)
        self.label__keyword.setTextFormat(Qt.AutoText)
        self.textedit__keyword = QTextEdit(self.groupBox)
        self.textedit__keyword.setObjectName(u"textedit__keyword")
        self.textedit__keyword.setGeometry(QRect(80, 20, 251, 41))
        self.textedit__keyword.setMinimumSize(QSize(0, 41))
        font2 = QFont()
        font2.setPointSize(10)
        self.textedit__keyword.setFont(font2)
        self.groupBox_7 = QGroupBox(Form)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 307, 502, 101))
        self.textBrowser_result = QTextBrowser(self.groupBox_7)
        self.textBrowser_result.setObjectName(u"textBrowser_result")
        self.textBrowser_result.setGeometry(QRect(12, 17, 301, 70))
        self.textBrowser_result.setFont(font2)
        self.buttonBox__ok = QDialogButtonBox(self.groupBox_7)
        self.buttonBox__ok.setObjectName(u"buttonBox__ok")
        self.buttonBox__ok.setGeometry(QRect(410, 40, 80, 24))
        font3 = QFont()
        font3.setItalic(True)
        self.buttonBox__ok.setFont(font3)
        self.buttonBox__ok.setOrientation(Qt.Horizontal)
        self.buttonBox__ok.setStandardButtons(QDialogButtonBox.Ok)
        self.buttonBox__reset = QPushButton(self.groupBox_7)
        self.buttonBox__reset.setObjectName(u"buttonBox__reset")
        self.buttonBox__reset.setGeometry(QRect(322, 40, 80, 24))
        self.buttonBox__reset.setFont(font)
        self.buttonBox__reset.setAcceptDrops(False)
        self.buttonBox__reset.setAutoFillBackground(False)
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 95, 502, 99))
        self.groupBox_2.setFont(font)
        self.textBrowser__targetpath = QTextBrowser(self.groupBox_2)
        self.textBrowser__targetpath.setObjectName(u"textBrowser__targetpath")
        self.textBrowser__targetpath.setGeometry(QRect(12, 40, 391, 39))
        self.textBrowser__targetpath.setMinimumSize(QSize(0, 31))
        self.textBrowser__targetpath.setFont(font1)
        self.buttonBox__targetpath = QDialogButtonBox(self.groupBox_2)
        self.buttonBox__targetpath.setObjectName(u"buttonBox__targetpath")
        self.buttonBox__targetpath.setEnabled(True)
        self.buttonBox__targetpath.setGeometry(QRect(410, 47, 80, 24))
        self.buttonBox__targetpath.setFont(font)
        self.buttonBox__targetpath.setOrientation(Qt.Horizontal)
        self.buttonBox__targetpath.setStandardButtons(QDialogButtonBox.Open)
        self.groupBox__recent = QGroupBox(Form)
        self.groupBox__recent.setObjectName(u"groupBox__recent")
        self.groupBox__recent.setGeometry(QRect(360, 8, 151, 81))
        self.label__recent = QLabel(self.groupBox__recent)
        self.label__recent.setObjectName(u"label__recent")
        self.label__recent.setGeometry(QRect(12, 14, 121, 16))
        self.label__recent.setFont(font)
        self.comboBox__recent = QComboBox(self.groupBox__recent)
        self.comboBox__recent.setObjectName(u"comboBox__recent")
        self.comboBox__recent.setGeometry(QRect(10, 38, 131, 23))
        self.comboBox__recent.setFont(font1)

        self.retranslateUi(Form)

        self.buttonBox__reset.setDefault(True)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Finder_mk3.5.3", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Form", u" Save Path", None))
#if QT_CONFIG(tooltip)
        self.textBrowser__save.setToolTip(QCoreApplication.translate("Form", u"Save Path", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.buttonBox__save.setToolTip(QCoreApplication.translate("Form", u"Search Target Path", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox.setTitle("")
        self.label__keyword.setText(QCoreApplication.translate("Form", u"Keyword", None))
#if QT_CONFIG(tooltip)
        self.textedit__keyword.setToolTip(QCoreApplication.translate("Form", u"Keyword", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox_7.setTitle("")
#if QT_CONFIG(tooltip)
        self.textBrowser_result.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.buttonBox__ok.setToolTip(QCoreApplication.translate("Form", u"Launch Finder", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.buttonBox__reset.setToolTip(QCoreApplication.translate("Form", u"Clear All Attributes", None))
#endif // QT_CONFIG(tooltip)
        self.buttonBox__reset.setText(QCoreApplication.translate("Form", u"Clear", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u" Target Path", None))
#if QT_CONFIG(tooltip)
        self.textBrowser__targetpath.setToolTip(QCoreApplication.translate("Form", u"Target Path", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.buttonBox__targetpath.setToolTip(QCoreApplication.translate("Form", u"Search Target Path", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox__recent.setTitle("")
        self.label__recent.setText(QCoreApplication.translate("Form", u"Recent Files", None))
#if QT_CONFIG(tooltip)
        self.comboBox__recent.setToolTip(QCoreApplication.translate("Form", u"Show Recent Files", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

